apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-mariadb
  namespace: bookmedik
spec:
  encryptedData:
    password: AgB6BXEPuEtDh9lV4JyqPU85R+Nh9EbJQ+siHjQ3qRxIPR2U2gEp9RAiJzERH7ngrfNSDte83dwFNVcOEMNz5UtOIcZ9zab7GMiwoLJRndbp6u3fYGCZ8oHN8GnlJUzeMkvjfKruqWgrStEQ0uOWx5B+yZQ2YXhkKivneWYoHj2etgBSfC0c/qyf+vj581K7NTYflzfxBbU9a9ZiG8ZBqNGve0PBzQjGq1/9liRTtnzWv70JyoiVzlI9tymY112QSQtZBqyDLFjRla2oISUxEKAtQhLcrTdRV/BeX1vMZFW7qSx3XrfzbVqNAjgZJncyF+NtTJSgWA+AJ90weZwHchry5bPs1wM7vXyrOxHyUVP98r+8mSBS9Cu0v2+/Ws/idwwL3rGqm2Srk4TCcPRxXbPtRprljXDmDBPJqaRvKqZke8jQ5tfVjaZPRfzbYXyrR658rBAYgjj3KgO/OiXi4ES44KNthahK3OZyQRsc3+YI6DRSJkRTXwPn1RyB5/aoKHnzkwntTqxPT/t+qAPdMZXyLZ1q4NMfudHyStizAxTADp4XG9zkKiYPu6frz37pmR+er0pllWUt6FIvrgoQfsluBpIYHbCou81RYMPuLqU/nJonOs3umDo8lVfotqhcT2YiKXltEkAMlxxf1caEunJ8w00QwLhQ+wUVPCOJtgYpwSFI6VVdMgoLibWmwpe9d4u9DaupGcW813I=
    rootpass: AgCwRJErSA/ThPZuKW9x3RSXyrGuy+gjPg++uA13MzVI671pR+wQQwEqcBLkw55MGKSISEyN+HufppmMO0AxjUAWbPHcZku1Z34zk4dOpibmckQp7CIIfJLHcnRheBkIjOQM8Q7BC6IcqqXrmuenH/YbXAeRxShkckUtQnjMLmHDrd4C9RBZuMfbei/LXRozPdy5il7Q8BKm6u6rM6mgWiP822coJe4AIa1yrP/fG2ggRqMTQF0T3F2tXJbzgCOSO+XEbFEYCHTXqirgdnQ0CxiSjK6bIZSazKajQm7WPBqfXavIvFrAneviMTfuKc55/I1yHqJJkJj9nJe5qRbGBEbquvHvTk3AXK2GjEPiU2HxTQIvZYPq+eEJJhBjW3H98t8bqEDe5iHVlvjbz6TpmNUkmNhHBIG1Ir5Oqtcke1kseVnuWe8oQ9evhgn7AHvzCwZOFjIQMCQZWMVXchLMonQ+Ozn1rdgTbi9+zPdhciu3rRi/4H797oHZ9rKNQU0PNB51pLKBXxNqX5oa9HIcB3gPSqUtTg/n3KpcTHBqB7EaEDXHKmSJbmDQWQWaDK93Ma7zvN/wvor2qaP6RuIvn0zBBNvkLLxEu1KZFEpFWqGhbmY47GYVIdFxFbjVJV26EyA+YomKJ3wJWa5xV9zhNJ/WWsc523iUkIUTLcqML3/5wqy/lKtrzvi++QkGTVbOpinitytX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-mariadb
      namespace: bookmedik

